version: 2.1
workflows:
  test:
    jobs:
      - test:
          version: "3.7"
      - test:
          version: "3.8"
      - test:
          version: "3.9"
      - test:
          version: "3.10"
      - test:
          version: "3.11"

jobs:
  test:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: cimg/python:<< parameters.version >>
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            uv tool install rust-just
            uv sync --locked
      - run:
          name: run tests
          command: |
            just lint test
