version: 2.1
workflows:
  test:
    jobs:
      - test:
          version: "3.7"
      - test:
          version: "3.8"
      - test:
          version: "3.9"
      - test:
          version: "3.10"
      - test:
          version: "3.11"

jobs:
  test:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: cimg/python:<< parameters.version >>
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "setup.cfg" }}
            - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -e .[tests]
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "setup.cfg" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
